using System;
using Terraria;
using Terraria.Achievements;
using Terraria.GameContent.Achievements;

namespace Terraria.Initializers
{
	internal class AchievementInitializer
	{
		public AchievementInitializer()
		{
		}

		public static void Load()
		{
			if (Main.netMode == 2)
			{
				return;
			}
			Achievement achievement = new Achievement("TIMBER", "Timber!!", "Chop down your first tree.");
			short[] numArray = new short[] { 9, 619, 2504, 620, 2503, 2260, 621, 911, 1729 };
			achievement.AddCondition(ItemPickupCondition.Create(numArray));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("NO_HOBO", "No Hobo", "Build a house suitable enough for your first town NPC, such as the guide, to move into.");
			achievement.AddCondition(ProgressionEventCondition.Create(8));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("OBTAIN_HAMMER", "Stop! Hammer Time!", "Obtain your first hammer via crafting or otherwise.");
			short[] numArray1 = new short[] { 2775, 2746, 3505, 654, 3517, 7, 3493, 2780, 1513, 2516, 660, 3481, 657, 922, 3511, 2785, 3499, 3487, 196, 367, 104, 797, 2320, 787, 1234, 1262, 3465, 204, 217, 1507, 3524, 3522, 3525, 3523, 1305 };
			achievement.AddCondition(ItemPickupCondition.Create(numArray1));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("OOO_SHINY", "Ooo! Shiny!", "Mine your first nugget of ore with a pickaxe.");
			ushort[] numArray2 = new ushort[] { 7, 6, 9, 8, 166, 167, 168, 169, 22, 204, 58, 107, 108, 111, 221, 222, 223, 211 };
			achievement.AddCondition(TileDestroyedCondition.Create(numArray2));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("HEART_BREAKER", "Heart Breaker", "Discover and smash your first heart crystal underground.");
			ushort[] numArray3 = new ushort[] { 12 };
			achievement.AddCondition(TileDestroyedCondition.Create(numArray3));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("HEAVY_METAL", "Heavy Metal", "Obtain an anvil made from iron or lead.");
			short[] numArray4 = new short[] { 35, 716 };
			achievement.AddCondition(ItemPickupCondition.Create(numArray4));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("I_AM_LOOT", "I Am Loot!", "Discover a golden chest underground and take a peek at its contents.");
			achievement.AddCondition(CustomFlagCondition.Create("Peek"));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("STAR_POWER", "Star Power", "Craft a mana crystal out of fallen stars, and consume it.");
			achievement.AddCondition(CustomFlagCondition.Create("Use"));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("HOLD_ON_TIGHT", "Hold on Tight!", "Equip your first grappling hook.");
			achievement.AddCondition(CustomFlagCondition.Create("Equip"));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("EYE_ON_YOU", "Eye on You", "Defeat the Eye of Cthulhu, an ocular menace who only appears at night.");
			achievement.AddCondition(NPCKilledCondition.Create(4));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("SMASHING_POPPET", "Smashing, Poppet!", "Using explosives or your trusty hammer, smash a Shadow Orb or Crimson Heart in the evil parts of your world.");
			achievement.AddCondition(ProgressionEventCondition.Create(7));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("WORM_FODDER", "Worm Fodder", "Defeat the Eater of Worlds, a massive worm whom dwells in the corruption.");
			short[] numArray5 = new short[] { 13, 14, 15 };
			achievement.AddCondition(NPCKilledCondition.Create(numArray5));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("MASTERMIND", "Mastermind", "Defeat the Brain of Cthulhu, an enourmous demon brain which haunts the creeping crimson.");
			achievement.AddCondition(NPCKilledCondition.Create(266));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("WHERES_MY_HONEY", "Where's My Honey?", "Discover a large bee's hive deep in the jungle.");
			achievement.AddCondition(CustomFlagCondition.Create("Reach"));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("STING_OPERATION", "Sting Operation", "Defeat the Queen Bee, the matriarch of the jungle hives.");
			achievement.AddCondition(NPCKilledCondition.Create(222));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("BONED", "Boned", "Defeat Skeletron, the cursed guardian of the dungeon.");
			achievement.AddCondition(NPCKilledCondition.Create(35));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("DUNGEON_HEIST", "Dungeon Heist", "Steal a key from dungeon's undead denizens, and unlock one of their precious golden chests.");
			achievement.AddCondition(ItemPickupCondition.Create(327));
			achievement.AddCondition(ProgressionEventCondition.Create(19));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("ITS_GETTING_HOT_IN_HERE", "It's Getting Hot in Here", "Spelunk deep enough to reach the molten underworld.");
			achievement.AddCondition(CustomFlagCondition.Create("Reach"));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("MINER_FOR_FIRE", "Miner for Fire", "Craft a molten pickaxe using the hottest of materials.");
			achievement.AddCondition(ItemCraftCondition.Create(122));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("STILL_HUNGRY", "Still Hungry", "Defeat the Wall of Flesh, the master and core of the world who arises after a great, burning sacrifice.");
			short[] numArray6 = new short[] { 113, 114 };
			achievement.AddCondition(NPCKilledCondition.Create(numArray6));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("ITS_HARD", "It's Hard!", "Unleash the ancient spirits of light and darkness across your world, enabling much stronger foes and showering the world with dazzling treasures (and rainbows!).");
			achievement.AddCondition(ProgressionEventCondition.Create(9));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("BEGONE_EVIL", "Begone, Evil!", "Smash a demon or crimson altar with a powerful, holy hammer.");
			achievement.AddCondition(ProgressionEventCondition.Create(6));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("EXTRA_SHINY", "Extra Shiny!", "Mine a powerful ore that has been newly blessed upon your world.");
			ushort[] numArray7 = new ushort[] { 107, 108, 111, 221, 222, 223 };
			achievement.AddCondition(TileDestroyedCondition.Create(numArray7));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("HEAD_IN_THE_CLOUDS", "Head in the Clouds", "Equip a pair of wings.");
			achievement.AddCondition(CustomFlagCondition.Create("Equip"));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("LIKE_A_BOSS", "Like a Boss", "Obtain a boss-summoning item.");
			short[] numArray8 = new short[] { 1133, 1331, 1307, 267, 1293, 557, 544, 556, 560, 43, 70 };
			achievement.AddCondition(ItemPickupCondition.Create(numArray8));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("BUCKETS_OF_BOLTS", "Buckets of Bolts", "Defeat the three nocturnal mechanical menaces: the Twins, the Destroyer, and Skeletron Prime.");
			short[] numArray9 = new short[] { 125, 126 };
			achievement.AddCondition(NPCKilledCondition.Create(numArray9));
			short[] numArray10 = new short[] { 127, 134 };
			achievement.AddConditions(NPCKilledCondition.CreateMany(numArray10));
			achievement.UseConditionsCompletedTracker();
			Main.Achievements.Register(achievement);
			achievement = new Achievement("DRAX_ATTAX", "Drax Attax", "Craft a drax or pickaxe axe using hallowed bars, and the souls of the three mechanical bosses.");
			short[] numArray11 = new short[] { 579, 990 };
			achievement.AddCondition(ItemCraftCondition.Create(numArray11));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("PHOTOSYNTHESIS", "Photosynthesis", "Mine chlorophyte, an organic ore found deep among the thickest of flora.");
			ushort[] numArray12 = new ushort[] { 211 };
			achievement.AddCondition(TileDestroyedCondition.Create(numArray12));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("GET_A_LIFE", "Get a Life", "Consume a life fruit, which grows in the thick of subterranean jungle grass.");
			achievement.AddCondition(CustomFlagCondition.Create("Use"));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("THE_GREAT_SOUTHERN_PLANTKILL", "The Great Southern Plantkill", "Defeat Plantera, the overgrown monstrosity of the jungle's depths.");
			achievement.AddCondition(NPCKilledCondition.Create(262));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("TEMPLE_RAIDER", "Temple Raider", "Breach the impenetrable walls of the jungle temple.");
			ushort[] numArray13 = new ushort[] { 226 };
			achievement.AddCondition(TileDestroyedCondition.Create(numArray13));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("LIHZAHRDIAN_IDOL", "Lihzahrdian Idol", "Defeat Golem, the stone-faced ritualistic idol of the lihzahrd tribe.");
			achievement.AddCondition(NPCKilledCondition.Create(245));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("ROBBING_THE_GRAVE", "Robbing the Grave", "Obtain a rare treasure from a difficult monster in the dungeon.");
			short[] numArray14 = new short[] { 1513, 938, 963, 977, 1300, 1254, 1514, 679, 759, 1446, 1445, 1444, 1183, 1266, 671 };
			achievement.AddCondition(ItemPickupCondition.Create(numArray14));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("BIG_BOOTY", "Big Booty", "Unlock one of the dungeon's large, mysterious chests with a special key.");
			achievement.AddCondition(ProgressionEventCondition.Create(20));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("FISH_OUT_OF_WATER", "Fish Out of Water", "Defeat Duke Fishron, mutant terror of the sea.");
			achievement.AddCondition(NPCKilledCondition.Create(370));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("OBSESSIVE_DEVOTION", "Obsessive Devotion", "Defeat the Ancient Cultist, fanatical leader of the dungeon coven.");
			achievement.AddCondition(NPCKilledCondition.Create(439));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("STAR_DESTROYER", "Star Destroyer", "Defeat the four celestial towers of the moon.");
			short[] numArray15 = new short[] { 517, 422, 507, 493 };
			achievement.AddConditions(NPCKilledCondition.CreateMany(numArray15));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("CHAMPION_OF_TERRARIA", "Champion of Terraria", "Defeat the Moon Lord.");
			achievement.AddCondition(NPCKilledCondition.Create(398));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("BLOODBATH", "Bloodbath", "Survive a blood moon, a nocturnal event where the rivers run red and monsters swarm aplenty.");
			achievement.AddCondition(ProgressionEventCondition.Create(5));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("SLIPPERY_SHINOBI", "Slippery Shinobi", "Defeat King Slime, the lord of all things slimy.");
			achievement.AddCondition(NPCKilledCondition.Create(50));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("GOBLIN_PUNTER", "Goblin Punter", "Triumph over a goblin invasion, a ragtag regiment of crude, barbaric, pointy-eared warriors and their shadowflame sorcerers.");
			achievement.AddCondition(ProgressionEventCondition.Create(10));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("WALK_THE_PLANK", "Walk the Plank", "Triumph over a pirate invasion, a group of pillagers from the sea out for your booty... and your life!");
			achievement.AddCondition(ProgressionEventCondition.Create(11));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("KILL_THE_SUN", "Kill the Sun", "Survive a solar eclipse, a day darker than night filled with creatures of horror.");
			achievement.AddCondition(ProgressionEventCondition.Create(3));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("DO_YOU_WANT_TO_SLAY_A_SNOWMAN", "Do You Want to Slay a Snowman?", "Triumph over the frost legion, a festive family of maniacal snowman mobsters.");
			achievement.AddCondition(ProgressionEventCondition.Create(12));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("TIN_FOIL_HATTER", "Tin-Foil Hatter", "Triumph over a martian invasion, when beings from out of this world come to scramble your brains and probe you in uncomfortable places.");
			achievement.AddCondition(ProgressionEventCondition.Create(13));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("BALEFUL_HARVEST", "Baleful Harvest", "Reach the 15th wave of a pumpkin moon, where evil lurks among the autumn harvest.");
			achievement.AddCondition(ProgressionEventCondition.Create(15));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("ICE_SCREAM", "Ice Scream", "Reach the 15th wave of a frost moon, where the festive season quickly degrades into madness.");
			achievement.AddCondition(ProgressionEventCondition.Create(14));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("STICKY_SITUATION", "Sticky Situation", "Survive the slime rain, where gelatinous organisms fall from the sky in droves.");
			achievement.AddCondition(ProgressionEventCondition.Create(16));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("REAL_ESTATE_AGENT", "Real Estate Agent", "Have all possible town NPCs living in your world.");
			achievement.AddCondition(ProgressionEventCondition.Create(17));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("NOT_THE_BEES", "Not the Bees!", "Fire a Bee Gun while wearing a full set of Bee Armor.");
			achievement.AddCondition(CustomFlagCondition.Create("Use"));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("JEEPERS_CREEPERS", "Jeepers Creepers", "Stumble into a spider cavern in the underground.");
			achievement.AddCondition(CustomFlagCondition.Create("Reach"));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("FUNKYTOWN", "Funkytown", "Build or encounter a glowing mushroom field above the surface.");
			achievement.AddCondition(CustomFlagCondition.Create("Reach"));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("INTO_ORBIT", "Into Orbit", "You can only go down from here!");
			achievement.AddCondition(CustomFlagCondition.Create("Reach"));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("ROCK_BOTTOM", "Rock Bottom", "The only way is up!");
			achievement.AddCondition(CustomFlagCondition.Create("Reach"));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("MECHA_MAYHEM", "Mecha Mayhem", "Do battle against the Twins, the Destroyer, and Skeletron Prime simultaneously and emerge victorious.");
			achievement.AddCondition(ProgressionEventCondition.Create(21));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("GELATIN_WORLD_TOUR", "Gelatin World Tour", "Defeat every type of slime there is!");
			short[] numArray16 = new short[] { -5, -6, 1, 81, 71, -3, 147, 138, -10, 50, 59, 16, -7, 244, -8, -1, -2, 184, 204, 225, -9, 141, 183, -4 };
			achievement.AddConditions(NPCKilledCondition.CreateMany(numArray16));
			achievement.UseConditionsCompletedTracker();
			Main.Achievements.Register(achievement);
			achievement = new Achievement("FASHION_STATEMENT", "Fashion Statement", "Equip armor or vanity clothing in all three social slots.");
			achievement.AddCondition(CustomFlagCondition.Create("Equip"));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("VEHICULAR_MANSLAUGHTER", "Vehicular Manslaughter", "Defeat an enemy by running it over with a minecart.");
			achievement.AddCondition(CustomFlagCondition.Create("Hit"));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("BULLDOZER", "Bulldozer", "Destroy a total of 10,000 tiles.");
			achievement.AddCondition(CustomIntCondition.Create("Pick", 10000));
			achievement.UseTrackerFromCondition("Pick");
			Main.Achievements.Register(achievement);
			achievement = new Achievement("THERE_ARE_SOME_WHO_CALL_HIM", "There are Some Who Call Him...", "Kill Tim.");
			achievement.AddCondition(NPCKilledCondition.Create(45));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("DECEIVER_OF_FOOLS", "Deceiver of Fools", "Kill a nymph.");
			achievement.AddCondition(NPCKilledCondition.Create(196));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("SWORD_OF_THE_HERO", "Sword of the Hero", "Obtain a Terra Blade, forged from the finest blades of light and darkness.");
			achievement.AddCondition(ItemPickupCondition.Create(757));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("LUCKY_BREAK", "Lucky Break", "Survive a long fall with just a sliver of health remaining.");
			achievement.AddCondition(CustomFlagCondition.Create("Hit"));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("THROWING_LINES", "Throwing Lines", "Throw a yoyo.");
			achievement.AddCondition(CustomFlagCondition.Create("Use"));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("DYE_HARD", "Dye Hard", "Equip a dye in every possible dye slot.");
			achievement.AddCondition(CustomFlagCondition.Create("Equip"));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("SICK_THROW", "Sick Throw", "Obtain the Terrarian.");
			achievement.AddCondition(ItemPickupCondition.Create(3389));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("FREQUENT_FLYER", "The Frequent Flyer", "Spend over 1 gold being treated by the nurse.");
			achievement.AddCondition(CustomFloatCondition.Create("Pay", 10000f));
			achievement.UseTrackerFromCondition("Pay");
			Main.Achievements.Register(achievement);
			achievement = new Achievement("THE_CAVALRY", "The Cavalry", "Equip a mount.");
			achievement.AddCondition(CustomFlagCondition.Create("Equip"));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("COMPLETELY_AWESOME", "Completely Awesome", "Obtain a minishark.");
			achievement.AddCondition(ItemPickupCondition.Create(98));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("TIL_DEATH", "Til Death...", "Kill the groom.");
			achievement.AddCondition(NPCKilledCondition.Create(53));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("ARCHAEOLOGIST", "Archaeologist", "Kill Doctor Bones.");
			achievement.AddCondition(NPCKilledCondition.Create(52));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("PRETTY_IN_PINK", "Pretty in Pink", "Kill pinky.");
			achievement.AddCondition(NPCKilledCondition.Create(-4));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("RAINBOWS_AND_UNICORNS", "Rainbows and Unicorns", "Fire a rainbow gun while riding on a unicorn.");
			achievement.AddCondition(CustomFlagCondition.Create("Use"));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("YOU_AND_WHAT_ARMY", "You and What Army?", "Command nine summoned minions simultaneously.");
			achievement.AddCondition(CustomFlagCondition.Create("Spawn"));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("PRISMANCER", "Prismancer", "Obtain a rainbow rod.");
			achievement.AddCondition(ItemPickupCondition.Create(495));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("IT_CAN_TALK", "It Can Talk?!", "Build a house in a mushroom biome and have Truffle move in.");
			achievement.AddCondition(ProgressionEventCondition.Create(18));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("WATCH_YOUR_STEP", "Watch Your Step!", "Become a victim to a nasty underground trap.");
			achievement.AddCondition(CustomFlagCondition.Create("Hit"));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("MARATHON_MEDALIST", "Marathon Medalist", "Travel a total of 26.2 miles on foot.");
			achievement.AddCondition(CustomFloatCondition.Create("Move", 1106688f));
			achievement.UseTrackerFromCondition("Move");
			Main.Achievements.Register(achievement);
			achievement = new Achievement("GLORIOUS_GOLDEN_POLE", "Glorious Golden Pole", "Obtain a golden fishing rod.");
			achievement.AddCondition(ItemPickupCondition.Create(2294));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("SERVANT_IN_TRAINING", "Servant-in-Training", "Complete your 1st quest for the angler.");
			achievement.AddCondition(CustomFlagCondition.Create("Finish"));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("GOOD_LITTLE_SLAVE", "Good Little Slave", "Complete your 10th quest for the angler.");
			achievement.AddCondition(CustomFloatCondition.Create("Finish", 10f));
			achievement.UseTrackerFromCondition("Finish");
			Main.Achievements.Register(achievement);
			achievement = new Achievement("TROUT_MONKEY", "Trout Monkey", "Complete your 25th quest for the angler.");
			achievement.AddCondition(CustomFloatCondition.Create("Finish", 25f));
			achievement.UseTrackerFromCondition("Finish");
			Main.Achievements.Register(achievement);
			achievement = new Achievement("FAST_AND_FISHIOUS", "Fast and Fishious", "Complete your 50th quest for the angler.");
			achievement.AddCondition(CustomFloatCondition.Create("Finish", 50f));
			achievement.UseTrackerFromCondition("Finish");
			Main.Achievements.Register(achievement);
			achievement = new Achievement("SUPREME_HELPER_MINION", "Supreme Helper Minion!", "Complete a grand total of 200 quests for the angler.");
			achievement.AddCondition(CustomFloatCondition.Create("Finish", 200f));
			achievement.UseTrackerFromCondition("Finish");
			Main.Achievements.Register(achievement);
			achievement = new Achievement("TOPPED_OFF", "Topped Off", "Attain maximum health and mana possible without accessories or buffs.");
			achievement.AddCondition(CustomFlagCondition.Create("Use"));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("SLAYER_OF_WORLDS", "Slayer of Worlds", "Defeat every boss in Terraria.");
			short[] numArray17 = new short[] { 13, 14, 15 };
			achievement.AddCondition(NPCKilledCondition.Create(numArray17));
			short[] numArray18 = new short[] { 113, 114 };
			achievement.AddCondition(NPCKilledCondition.Create(numArray18));
			short[] numArray19 = new short[] { 125, 126 };
			achievement.AddCondition(NPCKilledCondition.Create(numArray19));
			short[] numArray20 = new short[] { 4, 35, 50, 222, 113, 134, 127, 262, 245, 439, 398, 370 };
			achievement.AddConditions(NPCKilledCondition.CreateMany(numArray20));
			achievement.UseConditionsCompletedTracker();
			Main.Achievements.Register(achievement);
			achievement = new Achievement("YOU_CAN_DO_IT", "You Can Do It!", "Survive your character's first full night.");
			achievement.AddCondition(ProgressionEventCondition.Create(1));
			Main.Achievements.Register(achievement);
			achievement = new Achievement("MATCHING_ATTIRE", "Matching Attire", "Equip armor in all three armor slots: head, chest, and feet.");
			achievement.AddCondition(CustomFlagCondition.Create("Equip"));
			Main.Achievements.Register(achievement);
			int num = 0;
			int num1 = num + 1;
			Main.Achievements.RegisterIconIndex("TIMBER", num);
			int num2 = num1;
			num1 = num2 + 1;
			Main.Achievements.RegisterIconIndex("NO_HOBO", num2);
			int num3 = num1;
			num1 = num3 + 1;
			Main.Achievements.RegisterIconIndex("OBTAIN_HAMMER", num3);
			int num4 = num1;
			num1 = num4 + 1;
			Main.Achievements.RegisterIconIndex("HEART_BREAKER", num4);
			int num5 = num1;
			num1 = num5 + 1;
			Main.Achievements.RegisterIconIndex("OOO_SHINY", num5);
			int num6 = num1;
			num1 = num6 + 1;
			Main.Achievements.RegisterIconIndex("HEAVY_METAL", num6);
			int num7 = num1;
			num1 = num7 + 1;
			Main.Achievements.RegisterIconIndex("I_AM_LOOT", num7);
			int num8 = num1;
			num1 = num8 + 1;
			Main.Achievements.RegisterIconIndex("STAR_POWER", num8);
			int num9 = num1;
			num1 = num9 + 1;
			Main.Achievements.RegisterIconIndex("HOLD_ON_TIGHT", num9);
			int num10 = num1;
			num1 = num10 + 1;
			Main.Achievements.RegisterIconIndex("EYE_ON_YOU", num10);
			int num11 = num1;
			num1 = num11 + 1;
			Main.Achievements.RegisterIconIndex("SMASHING_POPPET", num11);
			int num12 = num1;
			num1 = num12 + 1;
			Main.Achievements.RegisterIconIndex("WORM_FODDER", num12);
			int num13 = num1;
			num1 = num13 + 1;
			Main.Achievements.RegisterIconIndex("MASTERMIND", num13);
			int num14 = num1;
			num1 = num14 + 1;
			Main.Achievements.RegisterIconIndex("WHERES_MY_HONEY", num14);
			int num15 = num1;
			num1 = num15 + 1;
			Main.Achievements.RegisterIconIndex("STING_OPERATION", num15);
			int num16 = num1;
			num1 = num16 + 1;
			Main.Achievements.RegisterIconIndex("BONED", num16);
			int num17 = num1;
			num1 = num17 + 1;
			Main.Achievements.RegisterIconIndex("DUNGEON_HEIST", num17);
			int num18 = num1;
			num1 = num18 + 1;
			Main.Achievements.RegisterIconIndex("ITS_GETTING_HOT_IN_HERE", num18);
			int num19 = num1;
			num1 = num19 + 1;
			Main.Achievements.RegisterIconIndex("MINER_FOR_FIRE", num19);
			int num20 = num1;
			num1 = num20 + 1;
			Main.Achievements.RegisterIconIndex("STILL_HUNGRY", num20);
			int num21 = num1;
			num1 = num21 + 1;
			Main.Achievements.RegisterIconIndex("ITS_HARD", num21);
			int num22 = num1;
			num1 = num22 + 1;
			Main.Achievements.RegisterIconIndex("BEGONE_EVIL", num22);
			int num23 = num1;
			num1 = num23 + 1;
			Main.Achievements.RegisterIconIndex("EXTRA_SHINY", num23);
			int num24 = num1;
			num1 = num24 + 1;
			Main.Achievements.RegisterIconIndex("HEAD_IN_THE_CLOUDS", num24);
			int num25 = num1;
			num1 = num25 + 1;
			Main.Achievements.RegisterIconIndex("LIKE_A_BOSS", num25);
			int num26 = num1;
			num1 = num26 + 1;
			Main.Achievements.RegisterIconIndex("BUCKETS_OF_BOLTS", num26);
			int num27 = num1;
			num1 = num27 + 1;
			Main.Achievements.RegisterIconIndex("DRAX_ATTAX", num27);
			int num28 = num1;
			num1 = num28 + 1;
			Main.Achievements.RegisterIconIndex("PHOTOSYNTHESIS", num28);
			int num29 = num1;
			num1 = num29 + 1;
			Main.Achievements.RegisterIconIndex("GET_A_LIFE", num29);
			int num30 = num1;
			num1 = num30 + 1;
			Main.Achievements.RegisterIconIndex("THE_GREAT_SOUTHERN_PLANTKILL", num30);
			int num31 = num1;
			num1 = num31 + 1;
			Main.Achievements.RegisterIconIndex("TEMPLE_RAIDER", num31);
			int num32 = num1;
			num1 = num32 + 1;
			Main.Achievements.RegisterIconIndex("LIHZAHRDIAN_IDOL", num32);
			int num33 = num1;
			num1 = num33 + 1;
			Main.Achievements.RegisterIconIndex("ROBBING_THE_GRAVE", num33);
			int num34 = num1;
			num1 = num34 + 1;
			Main.Achievements.RegisterIconIndex("BIG_BOOTY", num34);
			int num35 = num1;
			num1 = num35 + 1;
			Main.Achievements.RegisterIconIndex("FISH_OUT_OF_WATER", num35);
			int num36 = num1;
			num1 = num36 + 1;
			Main.Achievements.RegisterIconIndex("OBSESSIVE_DEVOTION", num36);
			int num37 = num1;
			num1 = num37 + 1;
			Main.Achievements.RegisterIconIndex("STAR_DESTROYER", num37);
			int num38 = num1;
			num1 = num38 + 1;
			Main.Achievements.RegisterIconIndex("CHAMPION_OF_TERRARIA", num38);
			int num39 = num1;
			num1 = num39 + 1;
			Main.Achievements.RegisterIconIndex("BLOODBATH", num39);
			int num40 = num1;
			num1 = num40 + 1;
			Main.Achievements.RegisterIconIndex("GOBLIN_PUNTER", num40);
			int num41 = num1;
			num1 = num41 + 1;
			Main.Achievements.RegisterIconIndex("KILL_THE_SUN", num41);
			int num42 = num1;
			num1 = num42 + 1;
			Main.Achievements.RegisterIconIndex("WALK_THE_PLANK", num42);
			int num43 = num1;
			num1 = num43 + 1;
			Main.Achievements.RegisterIconIndex("DO_YOU_WANT_TO_SLAY_A_SNOWMAN", num43);
			int num44 = num1;
			num1 = num44 + 1;
			Main.Achievements.RegisterIconIndex("TIN_FOIL_HATTER", num44);
			int num45 = num1;
			num1 = num45 + 1;
			Main.Achievements.RegisterIconIndex("BALEFUL_HARVEST", num45);
			int num46 = num1;
			num1 = num46 + 1;
			Main.Achievements.RegisterIconIndex("ICE_SCREAM", num46);
			int num47 = num1;
			num1 = num47 + 1;
			Main.Achievements.RegisterIconIndex("SLIPPERY_SHINOBI", num47);
			int num48 = num1;
			num1 = num48 + 1;
			Main.Achievements.RegisterIconIndex("STICKY_SITUATION", num48);
			int num49 = num1;
			num1 = num49 + 1;
			Main.Achievements.RegisterIconIndex("REAL_ESTATE_AGENT", num49);
			int num50 = num1;
			num1 = num50 + 1;
			Main.Achievements.RegisterIconIndex("NOT_THE_BEES", num50);
			int num51 = num1;
			num1 = num51 + 1;
			Main.Achievements.RegisterIconIndex("JEEPERS_CREEPERS", num51);
			int num52 = num1;
			num1 = num52 + 1;
			Main.Achievements.RegisterIconIndex("FUNKYTOWN", num52);
			int num53 = num1;
			num1 = num53 + 1;
			Main.Achievements.RegisterIconIndex("INTO_ORBIT", num53);
			int num54 = num1;
			num1 = num54 + 1;
			Main.Achievements.RegisterIconIndex("ROCK_BOTTOM", num54);
			int num55 = num1;
			num1 = num55 + 1;
			Main.Achievements.RegisterIconIndex("MECHA_MAYHEM", num55);
			int num56 = num1;
			num1 = num56 + 1;
			Main.Achievements.RegisterIconIndex("GELATIN_WORLD_TOUR", num56);
			int num57 = num1;
			num1 = num57 + 1;
			Main.Achievements.RegisterIconIndex("FASHION_STATEMENT", num57);
			int num58 = num1;
			num1 = num58 + 1;
			Main.Achievements.RegisterIconIndex("VEHICULAR_MANSLAUGHTER", num58);
			int num59 = num1;
			num1 = num59 + 1;
			Main.Achievements.RegisterIconIndex("BULLDOZER", num59);
			int num60 = num1;
			num1 = num60 + 1;
			Main.Achievements.RegisterIconIndex("THERE_ARE_SOME_WHO_CALL_HIM", num60);
			int num61 = num1;
			num1 = num61 + 1;
			Main.Achievements.RegisterIconIndex("DECEIVER_OF_FOOLS", num61);
			int num62 = num1;
			num1 = num62 + 1;
			Main.Achievements.RegisterIconIndex("SWORD_OF_THE_HERO", num62);
			int num63 = num1;
			num1 = num63 + 1;
			Main.Achievements.RegisterIconIndex("LUCKY_BREAK", num63);
			int num64 = num1;
			num1 = num64 + 1;
			Main.Achievements.RegisterIconIndex("THROWING_LINES", num64);
			int num65 = num1;
			num1 = num65 + 1;
			Main.Achievements.RegisterIconIndex("DYE_HARD", num65);
			int num66 = num1;
			num1 = num66 + 1;
			Main.Achievements.RegisterIconIndex("FREQUENT_FLYER", num66);
			int num67 = num1;
			num1 = num67 + 1;
			Main.Achievements.RegisterIconIndex("THE_CAVALRY", num67);
			int num68 = num1;
			num1 = num68 + 1;
			Main.Achievements.RegisterIconIndex("COMPLETELY_AWESOME", num68);
			int num69 = num1;
			num1 = num69 + 1;
			Main.Achievements.RegisterIconIndex("TIL_DEATH", num69);
			int num70 = num1;
			num1 = num70 + 1;
			Main.Achievements.RegisterIconIndex("ARCHAEOLOGIST", num70);
			int num71 = num1;
			num1 = num71 + 1;
			Main.Achievements.RegisterIconIndex("PRETTY_IN_PINK", num71);
			int num72 = num1;
			num1 = num72 + 1;
			Main.Achievements.RegisterIconIndex("RAINBOWS_AND_UNICORNS", num72);
			int num73 = num1;
			num1 = num73 + 1;
			Main.Achievements.RegisterIconIndex("YOU_AND_WHAT_ARMY", num73);
			int num74 = num1;
			num1 = num74 + 1;
			Main.Achievements.RegisterIconIndex("PRISMANCER", num74);
			int num75 = num1;
			num1 = num75 + 1;
			Main.Achievements.RegisterIconIndex("IT_CAN_TALK", num75);
			int num76 = num1;
			num1 = num76 + 1;
			Main.Achievements.RegisterIconIndex("WATCH_YOUR_STEP", num76);
			int num77 = num1;
			num1 = num77 + 1;
			Main.Achievements.RegisterIconIndex("MARATHON_MEDALIST", num77);
			int num78 = num1;
			num1 = num78 + 1;
			Main.Achievements.RegisterIconIndex("GLORIOUS_GOLDEN_POLE", num78);
			int num79 = num1;
			num1 = num79 + 1;
			Main.Achievements.RegisterIconIndex("SERVANT_IN_TRAINING", num79);
			int num80 = num1;
			num1 = num80 + 1;
			Main.Achievements.RegisterIconIndex("GOOD_LITTLE_SLAVE", num80);
			int num81 = num1;
			num1 = num81 + 1;
			Main.Achievements.RegisterIconIndex("TROUT_MONKEY", num81);
			int num82 = num1;
			num1 = num82 + 1;
			Main.Achievements.RegisterIconIndex("FAST_AND_FISHIOUS", num82);
			int num83 = num1;
			num1 = num83 + 1;
			Main.Achievements.RegisterIconIndex("SUPREME_HELPER_MINION", num83);
			int num84 = num1;
			num1 = num84 + 1;
			Main.Achievements.RegisterIconIndex("TOPPED_OFF", num84);
			int num85 = num1;
			num1 = num85 + 1;
			Main.Achievements.RegisterIconIndex("SLAYER_OF_WORLDS", num85);
			int num86 = num1;
			num1 = num86 + 1;
			Main.Achievements.RegisterIconIndex("YOU_CAN_DO_IT", num86);
			int num87 = num1;
			num1 = num87 + 1;
			Main.Achievements.RegisterIconIndex("SICK_THROW", num87);
			int num88 = num1;
			num1 = num88 + 1;
			Main.Achievements.RegisterIconIndex("MATCHING_ATTIRE", num88);
			AchievementCategory achievementCategory = AchievementCategory.Slayer;
			Main.Achievements.RegisterAchievementCategory("EYE_ON_YOU", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("SLIPPERY_SHINOBI", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("WORM_FODDER", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("MASTERMIND", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("STING_OPERATION", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("BONED", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("STILL_HUNGRY", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("BUCKETS_OF_BOLTS", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("THE_GREAT_SOUTHERN_PLANTKILL", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("LIHZAHRDIAN_IDOL", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("FISH_OUT_OF_WATER", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("OBSESSIVE_DEVOTION", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("STAR_DESTROYER", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("CHAMPION_OF_TERRARIA", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("GOBLIN_PUNTER", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("DO_YOU_WANT_TO_SLAY_A_SNOWMAN", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("WALK_THE_PLANK", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("BALEFUL_HARVEST", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("ICE_SCREAM", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("TIN_FOIL_HATTER", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("TIL_DEATH", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("THERE_ARE_SOME_WHO_CALL_HIM", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("ARCHAEOLOGIST", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("PRETTY_IN_PINK", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("DECEIVER_OF_FOOLS", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("VEHICULAR_MANSLAUGHTER", achievementCategory);
			achievementCategory = AchievementCategory.Explorer;
			Main.Achievements.RegisterAchievementCategory("SMASHING_POPPET", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("BEGONE_EVIL", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("ITS_HARD", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("FUNKYTOWN", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("WATCH_YOUR_STEP", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("YOU_CAN_DO_IT", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("BLOODBATH", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("KILL_THE_SUN", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("STICKY_SITUATION", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("NO_HOBO", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("IT_CAN_TALK", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("HEART_BREAKER", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("I_AM_LOOT", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("ROBBING_THE_GRAVE", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("GET_A_LIFE", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("JEEPERS_CREEPERS", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("WHERES_MY_HONEY", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("DUNGEON_HEIST", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("BIG_BOOTY", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("ITS_GETTING_HOT_IN_HERE", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("INTO_ORBIT", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("ROCK_BOTTOM", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("OOO_SHINY", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("EXTRA_SHINY", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("PHOTOSYNTHESIS", achievementCategory);
			achievementCategory = AchievementCategory.Challenger;
			Main.Achievements.RegisterAchievementCategory("GELATIN_WORLD_TOUR", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("SLAYER_OF_WORLDS", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("REAL_ESTATE_AGENT", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("YOU_AND_WHAT_ARMY", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("TOPPED_OFF", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("MECHA_MAYHEM", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("BULLDOZER", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("NOT_THE_BEES", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("RAINBOWS_AND_UNICORNS", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("THROWING_LINES", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("FREQUENT_FLYER", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("LUCKY_BREAK", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("MARATHON_MEDALIST", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("SERVANT_IN_TRAINING", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("GOOD_LITTLE_SLAVE", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("TROUT_MONKEY", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("FAST_AND_FISHIOUS", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("SUPREME_HELPER_MINION", achievementCategory);
			achievementCategory = AchievementCategory.Collector;
			Main.Achievements.RegisterAchievementCategory("OBTAIN_HAMMER", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("HEAVY_METAL", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("STAR_POWER", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("MINER_FOR_FIRE", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("HEAD_IN_THE_CLOUDS", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("DRAX_ATTAX", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("PRISMANCER", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("SWORD_OF_THE_HERO", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("HOLD_ON_TIGHT", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("THE_CAVALRY", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("DYE_HARD", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("MATCHING_ATTIRE", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("FASHION_STATEMENT", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("COMPLETELY_AWESOME", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("TIMBER", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("SICK_THROW", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("GLORIOUS_GOLDEN_POLE", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("TEMPLE_RAIDER", achievementCategory);
			Main.Achievements.RegisterAchievementCategory("LIKE_A_BOSS", achievementCategory);
			Main.Achievements.Load();
			Main.Achievements.OnAchievementCompleted += new Achievement.AchievementCompleted(AchievementInitializer.OnAchievementCompleted);
			AchievementsHelper.Initialize();
		}

		private static void OnAchievementCompleted(Achievement achievement)
		{
		}
	}
}