// Copyright (c) 2020 Pryaxis & Orion Contributors
// 
// This file is part of Orion.
// 
// Orion is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Orion is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Orion.  If not, see <https://www.gnu.org/licenses/>.

using System.Collections.Generic;


namespace TerrariaServerAPI.TerrariaApi.Server.Tiles.Entities;

/// <summary>
/// Specifies a block ID.
/// </summary>
/// <remarks>
/// This enumeration is offset from the internal Terraria block IDs by 1 in order to allow a `None` member to
/// occupy the 0 value.
/// </remarks>
public enum BlockId : ushort
{
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
	None = 0,
	Dirt = 1,
	Stone = 2,
	Grass = 3,
	ShortGrassPlants = 4,
	Torches = 5,
	Trees = 6,
	IronOre = 7,
	CopperOre = 8,
	GoldOre = 9,
	SilverOre = 10,
	ClosedDoors = 11,
	OpenDoors = 12,
	CrystalHeart = 13,
	Bottles = 14,
	Tables = 15,
	Chairs = 16,
	Anvils = 17,
	Furnace = 18,
	WorkBenches = 19,
	Platforms = 20,
	Acorn = 21,
	Chests = 22,
	DemoniteOre = 23,
	CorruptGrass = 24,
	ShortCorruptGrassPlants = 25,
	Ebonstone = 26,
	EvilAltars = 27,
	Sunflower = 28,
	Pots = 29,
	PiggyBank = 30,
	Wood = 31,
	EvilOrbs = 32,
	CorruptThornyBush = 33,
	Candles = 34,
	Chandeliers = 35,
	JackOLantern = 36,
	Present = 37,
	Meteorite = 38,
	GrayBrick = 39,
	RedBrick = 40,
	Clay = 41,
	BlueBrick = 42,
	Lanterns = 43,
	GreenBrick = 44,
	PinkBrick = 45,
	GoldBrick = 46,
	SilverBrick = 47,
	CopperBrick = 48,
	Spike = 49,
	WaterCandle = 50,
	Book = 51,
	Cobweb = 52,
	GrassVines = 53,
	Sand = 54,
	Glass = 55,
	Sign = 56,
	Obsidian = 57,
	Ash = 58,
	Hellstone = 59,
	Mud = 60,
	JungleGrass = 61,
	ShortJungleGrassPlants = 62,
	JungleGrassVines = 63,
	SapphireStone = 64,
	RubyStone = 65,
	EmeraldStone = 66,
	TopazStone = 67,
	AmethystStone = 68,
	DiamondStone = 69,
	JungleThornyBush = 70,
	MushroomGrass = 71,
	MushroomGrassPlants = 72,
	MushroomTrees = 73,
	TallGrassPlants = 74,
	TallJungleGrassPlants = 75,
	ObsidianBrick = 76,
	HellstoneBrick = 77,
	Hellforge = 78,
	ClayPot = 79,
	Beds = 80,
	CactusPlant = 81,
	Coral = 82,
	ImmatureHerbs = 83,
	MatureHerbs = 84,
	BloomingHerbs = 85,
	Tombstones = 86,
	Loom = 87,
	Pianos = 88,
	Dressers = 89,
	Benches = 90,
	Bathtubs = 91,
	Banners = 92,
	LampPost = 93,
	Lamps = 94,
	Keg = 95,
	ChineseLantern = 96,
	CookingPots = 97,
	Safe = 98,
	SkullLantern = 99,
	TrashCan = 100,
	Candelabras = 101,
	Bookcases = 102,
	Throne = 103,
	Bowls = 104,
	Clocks = 105,
	Statues = 106,
	Sawmill = 107,
	CobaltOre = 108,
	MythrilOre = 109,
	HallowedGrass = 110,
	ShortHallowedGrassPlants = 111,
	AdamantiteOre = 112,
	Ebonsand = 113,
	TallHallowedGrassPlants = 114,
	TinkerersWorkshop = 115,
	HallowedGrassVines = 116,
	Pearlsand = 117,
	Pearlstone = 118,
	PearlstoneBrick = 119,
	IridescentBrick = 120,
	MudstoneBrick = 121,
	CobaltBrick = 122,
	MythrilBrick = 123,
	Silt = 124,
	WoodenBeam = 125,
	CrystalBall = 126,
	DiscoBall = 127,
	IceRod = 128,
	Mannequin = 129,
	CrystalShard = 130,
	ActiveStone = 131,
	InactiveStone = 132,
	Lever = 133,
	HardmodeForges = 134,
	HardmodeAnvils = 135,
	PressurePlates = 136,
	Switch = 137,
	Traps = 138,
	Boulder = 139,
	MusicBoxes = 140,
	DemoniteBrick = 141,
	Explosives = 142,
	InletPump = 143,
	OutletPump = 144,
	Timers = 145,
	CandyCane = 146,
	GreenCandyCane = 147,
	Snow = 148,
	SnowBrick = 149,
	HolidayLights = 150,
	AdamantiteBeam = 151,
	SandstoneBrick = 152,
	EbonstoneBrick = 153,
	RedStucco = 154,
	YellowStucco = 155,
	GreenStucco = 156,
	GrayStucco = 157,
	Ebonwood = 158,
	RichMahogany = 159,
	Pearlwood = 160,
	RainbowBrick = 161,
	Ice = 162,
	ThinIce = 163,
	PurpleIce = 164,
	PinkIce = 165,
	AmbientObjects = 166,
	TinOre = 167,
	LeadOre = 168,
	TungstenOre = 169,
	PlatinumOre = 170,
	PineTree = 171,
	ChristmasTree = 172,
	Sinks = 173,
	PlatinumCandelabra = 174,
	PlatinumCandle = 175,
	TinBrick = 176,
	TungstenBrick = 177,
	PlatinumBrick = 178,
	Gems = 179,
	GreenMoss = 180,
	BrownMoss = 181,
	RedMoss = 182,
	BlueMoss = 183,
	PurpleMoss = 184,
	MossPlants = 185,
	SmallAmbientObjects = 186,
	LargeAmbientObjects = 187,
	LargeAmbientObjects2 = 188,
	Cactus = 189,
	Cloud = 190,
	GlowingMushroom = 191,
	LivingWood = 192,
	Leaf = 193,
	Slime = 194,
	Bone = 195,
	Flesh = 196,
	RainCloud = 197,
	FrozenSlime = 198,
	Asphalt = 199,
	CrimsonGrass = 200,
	RedIce = 201,
	ShortCrimsonGrassPlants = 202,
	Sunplate = 203,
	Crimstone = 204,
	CrimtaneOre = 205,
	CrimsonGrassVines = 206,
	IceBrick = 207,
	WaterFountains = 208,
	Shadewood = 209,
	Cannons = 210,
	LandMine = 211,
	ChlorophyteOre = 212,
	SnowballLauncher = 213,
	Rope = 214,
	Chain = 215,
	Campfires = 216,
	Fireworks = 217,
	BlendOMatic = 218,
	MeatGrinder = 219,
	Extractinator = 220,
	Solidifier = 221,
	PalladiumOre = 222,
	OrichalcumOre = 223,
	TitaniumOre = 224,
	Slush = 225,
	Hive = 226,
	LihzahrdBrick = 227,
	DyePlants = 228,
	DyeVat = 229,
	Honey = 230,
	CrispyHoney = 231,
	QueenBeeLarva = 232,
	WoodenSpike = 233,
	PlantDetritus = 234,
	Crimsand = 235,
	Teleporter = 236,
	LifeFruit = 237,
	LihzahrdAltar = 238,
	PlanteraBulb = 239,
	MetalBars = 240,
	Paintings3x3 = 241,
	Paintings4x3 = 242,
	Paintings6x4 = 243,
	ImbuingStation = 244,
	BubbleMachine = 245,
	Paintings2x3 = 246,
	Paintings3x2 = 247,
	Autohammer = 248,
	PalladiumColumn = 249,
	Bubblegum = 250,
	Titanstone = 251,
	Pumpkin = 252,
	Hay = 253,
	SpookyWood = 254,
	PumpkinSeed = 255,
	OfflineAmethystGemspark = 256,
	OfflineTopazGemspark = 257,
	OfflineSapphireGemspark = 258,
	OfflineEmeraldGemspark = 259,
	OfflineRubyGemspark = 260,
	OfflineDiamondGemspark = 261,
	OfflineAmberGemspark = 262,
	AmethystGemspark = 263,
	TopazGemspark = 264,
	SapphireGemspark = 265,
	EmeraldGemspark = 266,
	RubyGemspark = 267,
	DiamondGemspark = 268,
	AmberGemspark = 269,
	Womannequin = 270,
	FireflyInABottle = 271,
	LightningBugInABottle = 272,
	Cog = 273,
	StoneSlab = 274,
	SandstoneSlab = 275,
	BunnyCage = 276,
	SquirrelCage = 277,
	MallardDuckCage = 278,
	DuckCage = 279,
	BirdCage = 280,
	BlueJayCage = 281,
	CardinalCage = 282,
	FishBowl = 283,
	HeavyWorkBench = 284,
	CopperPlating = 285,
	SnailCage = 286,
	GlowingSnailCage = 287,
	AmmoBox = 288,
	MonarchButterflyJar = 289,
	PurpleEmperorButterflyJar = 290,
	RedAdmiralButterflyJar = 291,
	UlyssesButterflyJar = 292,
	SulphurButterflyJar = 293,
	TreeNymphButterflyJar = 294,
	ZebraSwallowtailButterflyJar = 295,
	JuliaButterflyJar = 296,
	ScorpionCage = 297,
	BlackScorpionCage = 298,
	FrogCage = 299,
	MouseCage = 300,
	BoneWelder = 301,
	FleshCloningVat = 302,
	GlassKiln = 303,
	LihzahrdFurnace = 304,
	LivingLoom = 305,
	SkyMill = 306,
	IceMachine = 307,
	SteampunkBoiler = 308,
	HoneyDispenser = 309,
	PenguinCage = 310,
	WormCage = 311,
	DynastyWood = 312,
	RedDynastyShingles = 313,
	BlueDynastyShingles = 314,
	Tracks = 315,
	Coralstone = 316,
	BlueJellyfishJar = 317,
	GreenJellyfishJar = 318,
	PinkJellyfishJar = 319,
	ShipInABottle = 320,
	SeaweedPlanter = 321,
	BorealWood = 322,
	PalmWood = 323,
	PalmTree = 324,
	Seashells = 325,
	TinPlating = 326,
	Waterfall = 327,
	Lavafall = 328,
	Confetti = 329,
	MidnightConfetti = 330,
	CopperCoin = 331,
	SilverCoin = 332,
	GoldCoin = 333,
	PlatinumCoin = 334,
	Racks = 335,
	FireworksBox = 336,
	LivingFire = 337,
	TextStatues = 338,
	FireworkFountain = 339,
	GrasshopperCage = 340,
	LivingCursedFire = 341,
	LivingDemonFire = 342,
	LivingFrostFire = 343,
	LivingIchor = 344,
	LivingUltrabrightFire = 345,
	Honeyfall = 346,
	ChlorophyteBrick = 347,
	CrimtaneBrick = 348,
	ShroomitePlating = 349,
	MushroomStatue = 350,
	MartianConduitPlating = 351,
	Smoke = 352,
	CrimsonThornyBush = 353,
	VineRope = 354,
	BewitchingTable = 355,
	AlchemyTable = 356,
	EnchantedSundial = 357,
	SmoothMarble = 358,
	GoldBirdCage = 359,
	GoldBunnyCage = 360,
	GoldButterflyJar = 361,
	GoldFrogCage = 362,
	GoldGrasshopperCage = 363,
	GoldMouseCage = 364,
	GoldWormCage = 365,
	SilkRope = 366,
	WebRope = 367,
	Marble = 368,
	Granite = 369,
	SmoothGranite = 370,
	MeteoriteBrick = 371,
	PinkSlime = 372,
	PeaceCandle = 373,
	MagicWaterDropper = 374,
	MagicLavaDropper = 375,
	MagicHoneyDropper = 376,
	Crates = 377,
	SharpeningStation = 378,
	TargetDummy = 379,
	Bubble = 380,
	PlanterBoxes = 381,
	LavaMoss = 382,
	GrassVineFlowers = 383,
	LivingMahogany = 384,
	MahoganyLeaf = 385,
	Crystal = 386,
	OpenTrapDoor = 387,
	ClosedTrapDoor = 388,
	ClosedTallGate = 389,
	OpenTallGate = 390,
	LavaLamp = 391,
	EnchantedNightcrawlerCage = 392,
	BuggyCage = 393,
	GrubbyCage = 394,
	SluggyCage = 395,
	ItemFrame = 396,
	Sandstone = 397,
	HardenedSand = 398,
	HardenedEbonsand = 399,
	HardenedCrimsand = 400,
	Ebonsandstone = 401,
	Crimsandstone = 402,
	HardenedPearlsand = 403,
	Pearlsandstone = 404,
	DesertFossil = 405,
	Fireplace = 406,
	Chimney = 407,
	SturdyFossil = 408,
	Luminite = 409,
	LuminiteBrick = 410,
	Monoliths = 411,
	Detonator = 412,
	AncientManipulator = 413,
	RedSquirrelCage = 414,
	GoldSquirrelCage = 415,
	SolarFragment = 416,
	VortexFragment = 417,
	NebulaFragment = 418,
	StardustFragment = 419,
	LogicGateLamps = 420,
	LogicGates = 421,
	ConveyorBeltClockwise = 422,
	ConveyorBeltCounterClockwise = 423,
	LogicSensors = 424,
	JunctionBox = 425,
	AnnouncementBox = 426,
	RedTeam = 427,
	RedTeamPlatform = 428,
	WeightedPressurePlates = 429,
	WireBulb = 430,
	GreenTeam = 431,
	BlueTeam = 432,
	YellowTeam = 433,
	PinkTeam = 434,
	WhiteTeam = 435,
	GreenTeamPlatform = 436,
	BlueTeamPlatform = 437,
	YellowTeamPlatform = 438,
	PinkTeamPlatform = 439,
	WhiteTeamPlatform = 440,
	GemLocks = 441,
	TrappedChests = 442,
	TealPressurePad = 443,
	Geyser = 444,
	Beehive = 445,
	PixelBox = 446,
	SillyPinkBalloon = 447,
	SillyPurpleBalloon = 448,
	SillyGreenBalloon = 449,
	BlueStreamer = 450,
	GreenStreamer = 451,
	PinkStreamer = 452,
	SillyBalloonMachine = 453,
	SillyTiedBalloons = 454,
	Pigronata = 455,
	PartyCenter = 456,
	SillyTiedBundleOfBalloons = 457,
	PartyPresent = 458,
	Sandfall = 459,
	Snowfall = 460,
	SnowCloud = 461,
	MagicSandDropper = 462,
	DesertSpiritLamp = 463,
	DefendersForge = 464,
	WarTable = 465,
	WarTableBanner = 466,
	EterniaCrystalStand = 467,
	Chests2 = 468,
	FakeChests2 = 469,
	Tables2 = 470,
	Mannequins = 471,
	WeaponRack = 472,
	IronBrick = 473,
	LeadBrick = 474,
	Lesion = 475,
	HatRack = 476,
	GolfCup = 477,
	GolfGrass = 478,
	CrimstoneBrick = 479,
	SmoothSandstone = 480,
	BloodMoonMonolith = 481,
	CrackedBlueBrick = 482,
	CrackedGreenBrick = 483,
	CrackedPinkBrick = 484,
	RollingCactus = 485,
	AntlionLarva = 486,
	DrumSet = 487,
	PicnicTables = 488,
	FallenLogs = 489,
	PinWheel = 490,
	WeatherVane = 491,
	VoidVault = 492,
	HallowedGolfGrass = 493,
	GolfCupFlag = 494,
	GolfTee = 495,
	ShellPile = 496,
	AntiPortal = 497,
	Toilets = 498,
	SpiderNest = 499,
	DecayChamber = 500,
	SolarBrick = 501,
	VortexBrick = 502,
	NebulaBrick = 503,
	StardustBrick = 504,
	SnakeRope = 505,
	GoldFishBowl = 506,
	BastStatue = 507,
	GoldStarry = 508,
	BlueStarry = 509,
	VoidMonolith = 510,
	ArrowSign = 511,
	PaintedArrowSign = 512,
	GreenMossBrick = 513,
	BrownMossBrick = 514,
	RedMossBrick = 515,
	BlueMossBrick = 516,
	PurpleMossBrick = 517,
	LavaMossBrick = 518,
	LilyPad = 519,
	Cattail = 520,
	Plate = 521,
	BlackDragonflyJar = 522,
	BlueDragonflyJar = 523,
	GreenDragonflyJar = 524,
	OrangeDragonflyJar = 525,
	RedDragonflyJar = 526,
	YellowDragonflyJar = 527,
	GoldDragonflyJar = 528,
	MushroomGrassVines = 529,
	SeaOats = 530,
	OasisPlants = 531,
	BoulderStatue = 532,
	MaggotCage = 533,
	RatCage = 534,
	KryptonMoss = 535,
	KryptonMossBrick = 536,
	XenonMoss = 537,
	XenonMossBrick = 538,
	LadybugCage = 539,
	ArgonMoss = 540,
	ArgonMossBrick = 541,
	Echo = 542,
	OwlCage = 543,
	PupfishBowl = 544,
	GoldLadybugCage = 545,
	LawnFlamingo = 546,
	Grate = 547,
	PottedPlants = 548,
	PottedPlants2 = 549,
	Seaweed = 550,
	TurtleCage = 551,
	JungleTurtleCage = 552,
	Sandcastles = 553,
	GrebeCage = 554,
	SeagullCage = 555,
	WaterStriderCage = 556,
	GoldWaterStriderCage = 557,
	ClosedGrate = 558,
	SeahorseCage = 559,
	GoldSeahorseCage = 560,
	GolfTrophies = 561,
	MarbleColumn = 562,
	Bamboo = 563,
	LargeBamboo = 564,
	PlasmaLamp = 565,
	FogMachine = 566,
	AmberStone = 567,
	GardenGnome = 568,
	PinkFairyJar = 569,
	GreenFairyJar = 570,
	BlueFairyJar = 571,
	BambooPlant = 572,
	SoulInABottles = 573,
	TatteredWoodSign = 574,
	BorealBeam = 575,
	RichMahoganyBeam = 576,
	GraniteColumn = 577,
	SandstoneColumn = 578,
	MushroomBeam = 579,
	RockGolemHead = 580,
	HellButterflyJar = 581,
	LavaflyInABottle = 582,
	MagmaSnailCage = 583,
	TopazTree = 584,
	AmethystTree = 585,
	SapphireTree = 586,
	EmeraldTree = 587,
	RubyTree = 588,
	DiamondTree = 589,
	AmberTree = 590,
	GemSaplings = 591,
	HangingPots = 592,
	HangingBrazier = 593,
	MiniVolcano = 594,
	LargeVolcano = 595,
	SakuraSapling = 596,
	SakuraTree = 597,
	TeleportationPylons = 598,
	LavaSerpentBowl = 599,
	AmethystBunnyCage = 600,
	TopazBunnyCage = 601,
	SapphireBunnyCage = 602,
	EmeraldBunnyCage = 603,
	RubyBunnyCage = 604,
	DiamondBunnyCage = 605,
	AmberBunnyCage = 606,
	AmethystSquirrelCage = 607,
	TopazSquirrelCage = 608,
	SapphireSquirrelCage = 609,
	EmeraldSquirrelCage = 610,
	RubySquirrelCage = 611,
	DiamondSquirrelCage = 612,
	AmberSquirrelCage = 613,
	PottedLavaPlants = 614,
	PottedEmberTendrils = 615,
	YellowWillowSapling = 616,
	YellowWillowTree = 617,
	BossRelics = 618,
	StoneAccentSlab = 619,
	TruffleWormCage = 620,
	PrismaticLacewingJar = 621,
	SliceOfCake = 622,
	Teapot = 623
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
}

/// <summary>
/// Provides extensions for the <see cref="BlockId"/> enumeration.
/// </summary>
public static class BlockIdExtensions
{
	private static readonly HashSet<BlockId> _frames = new HashSet<BlockId> {
		BlockId.ShortGrassPlants,
		BlockId.Torches,
		BlockId.Trees,
		BlockId.ClosedDoors,
		BlockId.OpenDoors,
		BlockId.CrystalHeart,
		BlockId.Bottles,
		BlockId.Tables,
		BlockId.Chairs,
		BlockId.Anvils,
		BlockId.Furnace,
		BlockId.WorkBenches,
		BlockId.Platforms,
		BlockId.Acorn,
		BlockId.Chests,
		BlockId.ShortCorruptGrassPlants,
		BlockId.EvilAltars,
		BlockId.Sunflower,
		BlockId.Pots,
		BlockId.PiggyBank,
		BlockId.EvilOrbs,
		BlockId.Candles,
		BlockId.Chandeliers,
		BlockId.JackOLantern,
		BlockId.Present,
		BlockId.Lanterns,
		BlockId.WaterCandle,
		BlockId.Book,
		BlockId.Sign,
		BlockId.ShortJungleGrassPlants,
		BlockId.MushroomGrassPlants,
		BlockId.MushroomTrees,
		BlockId.TallGrassPlants,
		BlockId.TallJungleGrassPlants,
		BlockId.Hellforge,
		BlockId.ClayPot,
		BlockId.Beds,
		BlockId.Coral,
		BlockId.ImmatureHerbs,
		BlockId.MatureHerbs,
		BlockId.BloomingHerbs,
		BlockId.Tombstones,
		BlockId.Loom,
		BlockId.Pianos,
		BlockId.Dressers,
		BlockId.Benches,
		BlockId.Bathtubs,
		BlockId.Banners,
		BlockId.LampPost,
		BlockId.Lamps,
		BlockId.Keg,
		BlockId.ChineseLantern,
		BlockId.CookingPots,
		BlockId.Safe,
		BlockId.SkullLantern,
		BlockId.TrashCan,
		BlockId.Candelabras,
		BlockId.Bookcases,
		BlockId.Throne,
		BlockId.Bowls,
		BlockId.Clocks,
		BlockId.Statues,
		BlockId.Sawmill,
		BlockId.ShortHallowedGrassPlants,
		BlockId.TallHallowedGrassPlants,
		BlockId.TinkerersWorkshop,
		BlockId.CrystalBall,
		BlockId.DiscoBall,
		BlockId.Mannequin,
		BlockId.CrystalShard,
		BlockId.Lever,
		BlockId.HardmodeForges,
		BlockId.HardmodeAnvils,
		BlockId.PressurePlates,
		BlockId.Switch,
		BlockId.Traps,
		BlockId.Boulder,
		BlockId.MusicBoxes,
		BlockId.Explosives,
		BlockId.InletPump,
		BlockId.OutletPump,
		BlockId.Timers,
		BlockId.HolidayLights,
		BlockId.AmbientObjects,
		BlockId.ChristmasTree,
		BlockId.Sinks,
		BlockId.PlatinumCandelabra,
		BlockId.PlatinumCandle,
		BlockId.Gems,
		BlockId.MossPlants,
		BlockId.SmallAmbientObjects,
		BlockId.LargeAmbientObjects,
		BlockId.LargeAmbientObjects2,
		BlockId.ShortCrimsonGrassPlants,
		BlockId.WaterFountains,
		BlockId.Cannons,
		BlockId.LandMine,
		BlockId.SnowballLauncher,
		BlockId.Campfires,
		BlockId.Fireworks,
		BlockId.BlendOMatic,
		BlockId.MeatGrinder,
		BlockId.Extractinator,
		BlockId.Solidifier,
		BlockId.DyePlants,
		BlockId.DyeVat,
		BlockId.QueenBeeLarva,
		BlockId.PlantDetritus,
		BlockId.Teleporter,
		BlockId.LifeFruit,
		BlockId.LihzahrdAltar,
		BlockId.PlanteraBulb,
		BlockId.MetalBars,
		BlockId.Paintings3x3,
		BlockId.Paintings4x3,
		BlockId.Paintings6x4,
		BlockId.ImbuingStation,
		BlockId.BubbleMachine,
		BlockId.Paintings2x3,
		BlockId.Paintings3x2,
		BlockId.Autohammer,
		BlockId.PumpkinSeed,
		BlockId.Womannequin,
		BlockId.FireflyInABottle,
		BlockId.LightningBugInABottle,
		BlockId.BunnyCage,
		BlockId.SquirrelCage,
		BlockId.MallardDuckCage,
		BlockId.DuckCage,
		BlockId.BirdCage,
		BlockId.BlueJayCage,
		BlockId.CardinalCage,
		BlockId.FishBowl,
		BlockId.HeavyWorkBench,
		BlockId.SnailCage,
		BlockId.GlowingSnailCage,
		BlockId.AmmoBox,
		BlockId.MonarchButterflyJar,
		BlockId.PurpleEmperorButterflyJar,
		BlockId.RedAdmiralButterflyJar,
		BlockId.UlyssesButterflyJar,
		BlockId.SulphurButterflyJar,
		BlockId.TreeNymphButterflyJar,
		BlockId.ZebraSwallowtailButterflyJar,
		BlockId.JuliaButterflyJar,
		BlockId.ScorpionCage,
		BlockId.BlackScorpionCage,
		BlockId.FrogCage,
		BlockId.MouseCage,
		BlockId.BoneWelder,
		BlockId.FleshCloningVat,
		BlockId.GlassKiln,
		BlockId.LihzahrdFurnace,
		BlockId.LivingLoom,
		BlockId.SkyMill,
		BlockId.IceMachine,
		BlockId.SteampunkBoiler,
		BlockId.HoneyDispenser,
		BlockId.PenguinCage,
		BlockId.WormCage,
		BlockId.Tracks,
		BlockId.BlueJellyfishJar,
		BlockId.GreenJellyfishJar,
		BlockId.PinkJellyfishJar,
		BlockId.ShipInABottle,
		BlockId.SeaweedPlanter,
		BlockId.PalmTree,
		BlockId.Seashells,
		BlockId.Racks,
		BlockId.FireworksBox,
		BlockId.TextStatues,
		BlockId.FireworkFountain,
		BlockId.GrasshopperCage,
		BlockId.MushroomStatue,
		BlockId.BewitchingTable,
		BlockId.AlchemyTable,
		BlockId.EnchantedSundial,
		BlockId.GoldBirdCage,
		BlockId.GoldBunnyCage,
		BlockId.GoldButterflyJar,
		BlockId.GoldFrogCage,
		BlockId.GoldGrasshopperCage,
		BlockId.GoldMouseCage,
		BlockId.GoldWormCage,
		BlockId.PeaceCandle,
		BlockId.MagicWaterDropper,
		BlockId.MagicLavaDropper,
		BlockId.MagicHoneyDropper,
		BlockId.Crates,
		BlockId.SharpeningStation,
		BlockId.TargetDummy,
		BlockId.PlanterBoxes,
		BlockId.OpenTrapDoor,
		BlockId.ClosedTrapDoor,
		BlockId.ClosedTallGate,
		BlockId.OpenTallGate,
		BlockId.LavaLamp,
		BlockId.EnchantedNightcrawlerCage,
		BlockId.BuggyCage,
		BlockId.GrubbyCage,
		BlockId.SluggyCage,
		BlockId.ItemFrame,
		BlockId.Fireplace,
		BlockId.Chimney,
		BlockId.Monoliths,
		BlockId.Detonator,
		BlockId.AncientManipulator,
		BlockId.RedSquirrelCage,
		BlockId.GoldSquirrelCage,
		BlockId.LogicGateLamps,
		BlockId.LogicGates,
		BlockId.LogicSensors,
		BlockId.JunctionBox,
		BlockId.AnnouncementBox,
		BlockId.RedTeamPlatform,
		BlockId.WeightedPressurePlates,
		BlockId.WireBulb,
		BlockId.GreenTeamPlatform,
		BlockId.BlueTeamPlatform,
		BlockId.YellowTeamPlatform,
		BlockId.PinkTeamPlatform,
		BlockId.WhiteTeamPlatform,
		BlockId.GemLocks,
		BlockId.TrappedChests,
		BlockId.TealPressurePad,
		BlockId.Geyser,
		BlockId.Beehive,
		BlockId.PixelBox,
		BlockId.SillyBalloonMachine,
		BlockId.SillyTiedBalloons,
		BlockId.Pigronata,
		BlockId.PartyCenter,
		BlockId.SillyTiedBundleOfBalloons,
		BlockId.PartyPresent,
		BlockId.MagicSandDropper,
		BlockId.DesertSpiritLamp,
		BlockId.DefendersForge,
		BlockId.WarTable,
		BlockId.WarTableBanner,
		BlockId.EterniaCrystalStand,
		BlockId.Chests2,
		BlockId.FakeChests2,
		BlockId.Tables2,
		BlockId.Mannequins,
		BlockId.WeaponRack,
		BlockId.HatRack,
		BlockId.GolfCup,
		BlockId.BloodMoonMonolith,
		BlockId.RollingCactus,
		BlockId.AntlionLarva,
		BlockId.DrumSet,
		BlockId.PicnicTables,
		BlockId.FallenLogs,
		BlockId.PinWheel,
		BlockId.WeatherVane,
		BlockId.VoidVault,
		BlockId.GolfCupFlag,
		BlockId.GolfTee,
		BlockId.Toilets,
		BlockId.DecayChamber,
		BlockId.GoldFishBowl,
		BlockId.BastStatue,
		BlockId.VoidMonolith,
		BlockId.ArrowSign,
		BlockId.PaintedArrowSign,
		BlockId.LilyPad,
		BlockId.Cattail,
		BlockId.Plate,
		BlockId.BlackDragonflyJar,
		BlockId.BlueDragonflyJar,
		BlockId.GreenDragonflyJar,
		BlockId.OrangeDragonflyJar,
		BlockId.RedDragonflyJar,
		BlockId.YellowDragonflyJar,
		BlockId.GoldDragonflyJar,
		BlockId.SeaOats,
		BlockId.OasisPlants,
		BlockId.BoulderStatue,
		BlockId.MaggotCage,
		BlockId.RatCage,
		BlockId.LadybugCage,
		BlockId.OwlCage,
		BlockId.PupfishBowl,
		BlockId.GoldLadybugCage,
		BlockId.LawnFlamingo,
		BlockId.PottedPlants,
		BlockId.PottedPlants2,
		BlockId.Seaweed,
		BlockId.TurtleCage,
		BlockId.JungleTurtleCage,
		BlockId.Sandcastles,
		BlockId.GrebeCage,
		BlockId.SeagullCage,
		BlockId.WaterStriderCage,
		BlockId.GoldWaterStriderCage,
		BlockId.SeahorseCage,
		BlockId.GoldSeahorseCage,
		BlockId.GolfTrophies,
		BlockId.PlasmaLamp,
		BlockId.FogMachine,
		BlockId.GardenGnome,
		BlockId.PinkFairyJar,
		BlockId.GreenFairyJar,
		BlockId.BlueFairyJar,
		BlockId.BambooPlant,
		BlockId.SoulInABottles,
		BlockId.TatteredWoodSign,
		BlockId.RockGolemHead,
		BlockId.HellButterflyJar,
		BlockId.LavaflyInABottle,
		BlockId.MagmaSnailCage,
		BlockId.TopazTree,
		BlockId.AmethystTree,
		BlockId.SapphireTree,
		BlockId.EmeraldTree,
		BlockId.RubyTree,
		BlockId.DiamondTree,
		BlockId.AmberTree,
		BlockId.GemSaplings,
		BlockId.HangingPots,
		BlockId.HangingBrazier,
		BlockId.MiniVolcano,
		BlockId.LargeVolcano,
		BlockId.SakuraSapling,
		BlockId.SakuraTree,
		BlockId.TeleportationPylons,
		BlockId.LavaSerpentBowl,
		BlockId.AmethystBunnyCage,
		BlockId.TopazBunnyCage,
		BlockId.SapphireBunnyCage,
		BlockId.EmeraldBunnyCage,
		BlockId.RubyBunnyCage,
		BlockId.DiamondBunnyCage,
		BlockId.AmberBunnyCage,
		BlockId.AmethystSquirrelCage,
		BlockId.TopazSquirrelCage,
		BlockId.SapphireSquirrelCage,
		BlockId.EmeraldSquirrelCage,
		BlockId.RubySquirrelCage,
		BlockId.DiamondSquirrelCage,
		BlockId.AmberSquirrelCage,
		BlockId.PottedLavaPlants,
		BlockId.PottedEmberTendrils,
		BlockId.YellowWillowSapling,
		BlockId.YellowWillowTree,
		BlockId.BossRelics,
		BlockId.TruffleWormCage,
		BlockId.PrismaticLacewingJar,
		BlockId.SliceOfCake,
		BlockId.Teapot
	};

	/// <summary>
	/// Returns a value indicating whether the block ID has frames.
	/// </summary>
	/// <param name="id">The block ID.</param>
	/// <returns><see langword="true"/> if the block ID has frames; otherwise, <see langword="false"/>.</returns>
	public static bool HasFrames(this BlockId id) => _frames.Contains(id);
}
